### ISSUE TITLE
custom home folder username not working 

### ISSUE THREAD

**Issue by lavenderdotpet** [CryoByte33/steam-deck-utilities#168]
```(2)(lavender@girldeck Downloads)$ ./cryo_utilities 
2023/12/09 21:18:50 open /home/lavender/.cryo_utilities/cryoutilities.log: no such file or directory
panic: open /home/lavender/.cryo_utilities/cryoutilities.log: no such file or directory

goroutine 1 [running, locked to thread]:
log.Panic({0xc00022fe50?, 0x30?, 0x42?})
        /opt/hostedtoolcache/go/1.21.4/x64/src/log/log.go:432 +0x5a
main.main()
        /home/runner/work/steam-deck-utilities/steam-deck-utilities/cmd/cryoutilities/main.go:37 +0xa6```

**Comment by lavenderdotpet** [comment]
disregard i forgot about the .desktop file
